# Generated by Django 6.0.3 on 2026-03-06 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_name', models.CharField(max_length=255)),
                ('sensor_date', models.DateTimeField()),
                ('data_info', models.JSONField()),
            ],
            options={
                'ordering': ['-sensor_date'],
            },
        ),
    ]
